# Hyperion CLMM Indexer Configuration
# This indexer tracks Hyperion liquidity pools, swaps, and price data on Aptos
# Discovered contract address via Aptos SDK query
health_check_port: 8085
server_config:
  processor_config:
    type: "contract_processor"
  transaction_stream_config:
    # Aptos Mainnet GRPC endpoint
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    # Starting version - adjust based on Hyperion deployment
    starting_version: 0
    # Go to https://developers.aptoslabs.com/ to create a project and get an API token
    auth_token: "YOUR_APTOS_API_TOKEN_HERE"
    request_name_header: ""
  db_config:
    # PostgreSQL connection string (Neon or other PostgreSQL DB)
    # Format: postgresql://username:password@host/database
    postgres_connection_string: "postgresql://username:password@neon_host/db_name"
    # Database connection pool size
    db_pool_size: 25
  contract_config:
    # Hyperion CLMM Module Address (REAL - discovered from blockchain)
    # This module deploys pool_v3::LiquidityPoolV3 resources
    # Verified pool: 0x925660b8618394809f89f8002e2926600c775221f43bf1919782b297a79400d8
    contract_address: "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c"
